#ifndef FALLOUT_PLIB_GNW_INPUT_REBIND_H_
#define FALLOUT_PLIB_GNW_INPUT_REBIND_H_

namespace fallout {

#define BIND_SECTION_NO_SEC "nosec"

typedef enum BindScreen {
    SCREEN_MAIN,
    SCREEN_GAME,
    SCREEN_CHAR,
    SCREEN_INV,
    SCREEN_PIP,
    SCREEN_INTERFACE,
    SCREEN_USE_ITEM,
    SCREEN_LOOT,
    SCREEN_BARTER,
    SCREEN_MOVE_ITEMS,
    SCREEN_SET_TIMER,
    SCREEN_DIALOG_OPTIONS,
    SCREEN_DIALOG_REPLY,
    SCREEN_DIALOG_REVIEW,
    SCREEN_DIALOG,
    SCREEN_DIALOG_ABOUT,
    SCREEN_LOAD_SAVE,
    SCREEN_SAVE_COMMENT,
    SCREEN_OPTIONS,
    SCREEN_PAUSE,
    SCREEN_PREFERENCES,
    SCREEN_CHAR_SELECT,
    SCREEN_SKILLDEX,
    SCREEN_ELEVATOR,
    SCREEN_MESSAGE,
    SCREEN_FILE_LOAD,
    SCREEN_FILE_SAVE,
    SCREEN_HALL_OF_FAME,
    SCREEN_HELP,
    SCREEN_CALLED_SHOT,
    SCREEN_PIP_STATUS,
    SCREEN_PIP_AUTOMAPS,
    SCREEN_PIP_ARCHIVES,
    SCREEN_PIP_ALARM,
    SCREEN_AUTOMAP,
    SCREEN_WORLD_MAP,
    SCREEN_TOWN_MAP,
    SCREEN_START_MESSAGE,
    SCREEN_EDITOR_NAME,
    SCREEN_EDITOR_AGE,
    SCREEN_EDITOR_SEX,
    SCREEN_EDITOR_OPTIONS,
    SCREEN_PERKS,
    SCREEN_MAX
} BindScreen;

extern int current_screen;

bool bind_init();
int get_key(int screen, int key);
int get_physical_key(int screen, int logical_key);

}

#endif // FALLOUT_PLIB_GNW_INPUT_REBIND_H_
