#
# cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain-mingw.cmake -G "Unix Makefiles" ..
#

set(CMAKE_SYSTEM_NAME Windows)
set(BIN_NAME x86_64-w64-mingw32)
set(CMAKE_SYSTEM_PROCESSOR x86_64) 

if("${ARCH}" STREQUAL "x86")
	set(BIN_NAME i686-w64-mingw32)
	set(CMAKE_SYSTEM_PROCESSOR i686) 
endif()

set(CMAKE_C_COMPILER ${BIN_NAME}-gcc)
set(CMAKE_CXX_COMPILER ${BIN_NAME}-g++)

set(CMAKE_FIND_ROOT_PATH ${BIN_NAME}-mingw32)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++ -static")

